services:
  mongodb:
    image: mongo:noble
    container_name: mongo
    restart: always
    volumes:
      - mongo_data:/data/db

  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=[REDACTED]
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    ports:
      - "9200:9200"

  graylog:
    image: graylog/graylog:6.3.1
    container_name: graylog
    environment:
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
      - GRAYLOG_PASSWORD_SECRET=[REDACTED]
      - GRAYLOG_ROOT_PASSWORD_SHA2=[REDACTED]
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://opensearch:9200
    depends_on:
      - mongodb
      - opensearch
    ports:
      - "9000:9000"         # Web interface
      - "12201:12201/udp"   # GELF UDP
      - "1514:1514/udp"     # Syslog UDP
    volumes:
      - graylog_data:/usr/share/graylog/data

volumes: